server:
  port: 8089

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: movie_review
  mvc:
    static-path-pattern: /static/**
  freemarker:
    expose-session-attributes: true

  #  DB
  datasource:
    url: jdbc:h2:./db/movie_review;AUTO_SERVER=TRUE
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.h2.Driver
  #  sql:
  #    init:
  #      mode: always
  jpa:
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:/db/changelog/master.yaml

  #  Email
  mail:
    host: smtp.gmail.com
    username: ${SMTP_USERNAME}
    password: ${SMTP_PWD}
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  #  OAuth
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH_CLIENT_ID}
            client-secret: ${OAUTH_CLIENT_SECRET}
            scope:
              - email
              - profile

logging:
  file:
    path: logs
  level:
    org:
      springframework:
        security: debug
    kg.attractor.movie_review: debug
    com.zaxxer.hikari: error
    org.apache.tomcat: error
    liquibase: error
    root: info
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n"